# -*- coding: utf-8 -*-
"""
Created on Thu Sep 24 20:00:33 2015

@author: zlatan.kremonic
"""


# 2
import timeit
""" 
Each new term in the Fibonacci sequence is generated by adding the 
previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not 
exceed four million, find the sum of the even-valued terms.
"""

x = [i for i in range(5,10)]
x[-2:]

np.max(x)

def Num_two(): 
    x = [1,2]
    
    while np.max(x) < 4000000:
        x.append(np.sum(x[-2:]))
    
    z = []
    for i in x[:-1]:
        if i % 2 == 0:
            z.append(i)
    
    return np.sum(z)

Num_two()